{{- if .Values.customCA.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "external-dns.fullname" . }}
  labels: {{ include "external-dns.labels" . | nindent 4 }}
data:
  {{ .Values.customCA.filename }}: |
{{ .Values.customCA.content | indent 4 }}
{{- end }}
